### ISSUE TITLE
Failed With Exit Code 1

### ISSUE THREAD

**Issue by coder110** [calebkleveter/Meteorologist#1]
I downloaded Meteorologist onto my computer and I'm running into this Swift compiler error...
```Swift
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```
Not sure what's wrong.
![screen shot 2017-12-06 at 12 19 29 pm](https://user-images.githubusercontent.com/25675097/33677863-cc189a74-da7f-11e7-8760-f264448295a5.png)

**Comment by calebkleveter** [comment]
Looks like you are missing the `Secure.swift` file, or something else is wrong with it. Try fixing that issue, then get back and give me an update.

**Comment by coder110** [comment]
Yep, that fixed it. I realized I hadn't read the ```README.md``` and added a ```secure.swift``` file. 
This is the first project I've done anything with on Github, sorry if it sounds stupid that I didn't read the readme. Looking back I'm not sure what I was thinking :p

**Comment by calebkleveter** [comment]
No worries 😄. Glad you figured it out!
